// Generated by gencpp from file vision_utils/Particles.msg
// DO NOT EDIT!


#ifndef VISION_UTILS_MESSAGE_PARTICLES_H
#define VISION_UTILS_MESSAGE_PARTICLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace vision_utils
{
template <class ContainerAllocator>
struct Particles_
{
  typedef Particles_<ContainerAllocator> Type;

  Particles_()
    : header()
    , particle()  {
    }
  Particles_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , particle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Quaternion_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Quaternion_<ContainerAllocator> >::other >  _particle_type;
  _particle_type particle;





  typedef boost::shared_ptr< ::vision_utils::Particles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_utils::Particles_<ContainerAllocator> const> ConstPtr;

}; // struct Particles_

typedef ::vision_utils::Particles_<std::allocator<void> > Particles;

typedef boost::shared_ptr< ::vision_utils::Particles > ParticlesPtr;
typedef boost::shared_ptr< ::vision_utils::Particles const> ParticlesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_utils::Particles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_utils::Particles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_utils

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vision_utils': ['/home/alfarobi/alfarobi_ws/src/ALFAROBI-Vision/vision_utils/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_utils::Particles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_utils::Particles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_utils::Particles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_utils::Particles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_utils::Particles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_utils::Particles_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_utils::Particles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "193233b6e6c22c2a199ab3f2b0fde1fa";
  }

  static const char* value(const ::vision_utils::Particles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x193233b6e6c22c2aULL;
  static const uint64_t static_value2 = 0x199ab3f2b0fde1faULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_utils::Particles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_utils/Particles";
  }

  static const char* value(const ::vision_utils::Particles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_utils::Particles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Quaternion[] particle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::vision_utils::Particles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_utils::Particles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.particle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Particles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_utils::Particles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_utils::Particles_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "particle[]" << std::endl;
    for (size_t i = 0; i < v.particle.size(); ++i)
    {
      s << indent << "  particle[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "    ", v.particle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_UTILS_MESSAGE_PARTICLES_H
