# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from feedback_msgs/FeedbackParam.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FeedbackParam(genpy.Message):
  _md5sum = "b6dc619d19217c2ba9bca0b28f4e3fda"
  _type = "feedback_msgs/FeedbackParam"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 Body_Height
float32 Body_Tilt
float32 Leg_X
float32 Leg_Y
float32 Leg_Z

float32 Leg_R_Z
float32 Leg_L_Z
float32 R_Roll
float32 L_Roll

float32 Setpoint_Pitch
float32 Setpoint_Roll

float32 Gain_Angle_Pitch
float32 Gain_Angle_Roll

float32 Gain_Velocity_Pitch
float32 Gain_Velocity_Roll

float32 Gain_Integral_Pitch
float32 Gain_Integral_Roll
"""
  __slots__ = ['Body_Height','Body_Tilt','Leg_X','Leg_Y','Leg_Z','Leg_R_Z','Leg_L_Z','R_Roll','L_Roll','Setpoint_Pitch','Setpoint_Roll','Gain_Angle_Pitch','Gain_Angle_Roll','Gain_Velocity_Pitch','Gain_Velocity_Roll','Gain_Integral_Pitch','Gain_Integral_Roll']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Body_Height,Body_Tilt,Leg_X,Leg_Y,Leg_Z,Leg_R_Z,Leg_L_Z,R_Roll,L_Roll,Setpoint_Pitch,Setpoint_Roll,Gain_Angle_Pitch,Gain_Angle_Roll,Gain_Velocity_Pitch,Gain_Velocity_Roll,Gain_Integral_Pitch,Gain_Integral_Roll

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FeedbackParam, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Body_Height is None:
        self.Body_Height = 0.
      if self.Body_Tilt is None:
        self.Body_Tilt = 0.
      if self.Leg_X is None:
        self.Leg_X = 0.
      if self.Leg_Y is None:
        self.Leg_Y = 0.
      if self.Leg_Z is None:
        self.Leg_Z = 0.
      if self.Leg_R_Z is None:
        self.Leg_R_Z = 0.
      if self.Leg_L_Z is None:
        self.Leg_L_Z = 0.
      if self.R_Roll is None:
        self.R_Roll = 0.
      if self.L_Roll is None:
        self.L_Roll = 0.
      if self.Setpoint_Pitch is None:
        self.Setpoint_Pitch = 0.
      if self.Setpoint_Roll is None:
        self.Setpoint_Roll = 0.
      if self.Gain_Angle_Pitch is None:
        self.Gain_Angle_Pitch = 0.
      if self.Gain_Angle_Roll is None:
        self.Gain_Angle_Roll = 0.
      if self.Gain_Velocity_Pitch is None:
        self.Gain_Velocity_Pitch = 0.
      if self.Gain_Velocity_Roll is None:
        self.Gain_Velocity_Roll = 0.
      if self.Gain_Integral_Pitch is None:
        self.Gain_Integral_Pitch = 0.
      if self.Gain_Integral_Roll is None:
        self.Gain_Integral_Roll = 0.
    else:
      self.Body_Height = 0.
      self.Body_Tilt = 0.
      self.Leg_X = 0.
      self.Leg_Y = 0.
      self.Leg_Z = 0.
      self.Leg_R_Z = 0.
      self.Leg_L_Z = 0.
      self.R_Roll = 0.
      self.L_Roll = 0.
      self.Setpoint_Pitch = 0.
      self.Setpoint_Roll = 0.
      self.Gain_Angle_Pitch = 0.
      self.Gain_Angle_Roll = 0.
      self.Gain_Velocity_Pitch = 0.
      self.Gain_Velocity_Roll = 0.
      self.Gain_Integral_Pitch = 0.
      self.Gain_Integral_Roll = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_17f().pack(_x.Body_Height, _x.Body_Tilt, _x.Leg_X, _x.Leg_Y, _x.Leg_Z, _x.Leg_R_Z, _x.Leg_L_Z, _x.R_Roll, _x.L_Roll, _x.Setpoint_Pitch, _x.Setpoint_Roll, _x.Gain_Angle_Pitch, _x.Gain_Angle_Roll, _x.Gain_Velocity_Pitch, _x.Gain_Velocity_Roll, _x.Gain_Integral_Pitch, _x.Gain_Integral_Roll))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.Body_Height, _x.Body_Tilt, _x.Leg_X, _x.Leg_Y, _x.Leg_Z, _x.Leg_R_Z, _x.Leg_L_Z, _x.R_Roll, _x.L_Roll, _x.Setpoint_Pitch, _x.Setpoint_Roll, _x.Gain_Angle_Pitch, _x.Gain_Angle_Roll, _x.Gain_Velocity_Pitch, _x.Gain_Velocity_Roll, _x.Gain_Integral_Pitch, _x.Gain_Integral_Roll,) = _get_struct_17f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_17f().pack(_x.Body_Height, _x.Body_Tilt, _x.Leg_X, _x.Leg_Y, _x.Leg_Z, _x.Leg_R_Z, _x.Leg_L_Z, _x.R_Roll, _x.L_Roll, _x.Setpoint_Pitch, _x.Setpoint_Roll, _x.Gain_Angle_Pitch, _x.Gain_Angle_Roll, _x.Gain_Velocity_Pitch, _x.Gain_Velocity_Roll, _x.Gain_Integral_Pitch, _x.Gain_Integral_Roll))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.Body_Height, _x.Body_Tilt, _x.Leg_X, _x.Leg_Y, _x.Leg_Z, _x.Leg_R_Z, _x.Leg_L_Z, _x.R_Roll, _x.L_Roll, _x.Setpoint_Pitch, _x.Setpoint_Roll, _x.Gain_Angle_Pitch, _x.Gain_Angle_Roll, _x.Gain_Velocity_Pitch, _x.Gain_Velocity_Roll, _x.Gain_Integral_Pitch, _x.Gain_Integral_Roll,) = _get_struct_17f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_17f = None
def _get_struct_17f():
    global _struct_17f
    if _struct_17f is None:
        _struct_17f = struct.Struct("<17f")
    return _struct_17f
