// Generated by gencpp from file mcl_localization/GetLocParam.msg
// DO NOT EDIT!


#ifndef MCL_LOCALIZATION_MESSAGE_GETLOCPARAM_H
#define MCL_LOCALIZATION_MESSAGE_GETLOCPARAM_H

#include <ros/service_traits.h>


#include <mcl_localization/GetLocParamRequest.h>
#include <mcl_localization/GetLocParamResponse.h>


namespace mcl_localization
{

struct GetLocParam
{

typedef GetLocParamRequest Request;
typedef GetLocParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLocParam
} // namespace mcl_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mcl_localization::GetLocParam > {
  static const char* value()
  {
    return "3909651f1afc562f3108e47d85479fbe";
  }

  static const char* value(const ::mcl_localization::GetLocParam&) { return value(); }
};

template<>
struct DataType< ::mcl_localization::GetLocParam > {
  static const char* value()
  {
    return "mcl_localization/GetLocParam";
  }

  static const char* value(const ::mcl_localization::GetLocParam&) { return value(); }
};


// service_traits::MD5Sum< ::mcl_localization::GetLocParamRequest> should match 
// service_traits::MD5Sum< ::mcl_localization::GetLocParam > 
template<>
struct MD5Sum< ::mcl_localization::GetLocParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mcl_localization::GetLocParam >::value();
  }
  static const char* value(const ::mcl_localization::GetLocParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcl_localization::GetLocParamRequest> should match 
// service_traits::DataType< ::mcl_localization::GetLocParam > 
template<>
struct DataType< ::mcl_localization::GetLocParamRequest>
{
  static const char* value()
  {
    return DataType< ::mcl_localization::GetLocParam >::value();
  }
  static const char* value(const ::mcl_localization::GetLocParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mcl_localization::GetLocParamResponse> should match 
// service_traits::MD5Sum< ::mcl_localization::GetLocParam > 
template<>
struct MD5Sum< ::mcl_localization::GetLocParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mcl_localization::GetLocParam >::value();
  }
  static const char* value(const ::mcl_localization::GetLocParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mcl_localization::GetLocParamResponse> should match 
// service_traits::DataType< ::mcl_localization::GetLocParam > 
template<>
struct DataType< ::mcl_localization::GetLocParamResponse>
{
  static const char* value()
  {
    return DataType< ::mcl_localization::GetLocParam >::value();
  }
  static const char* value(const ::mcl_localization::GetLocParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MCL_LOCALIZATION_MESSAGE_GETLOCPARAM_H
