Angle_4: 10
KD_0: 0.23
KD_2: 0
Gyro_4: 80
KD_4: 0.24
trunkPause: 0.5
trunkPitchPCoefTurn: 0
trunkHeight: 0.375
Angle_1: 7
setpointPitch: 1
KD_P_qw: 0
Angle_3: 8
Gyro_2: 0
KP_3: 0.1
trunkXOffsetPCoefForward: 0.5
Angle_2: 3
Gyro_1: 40
KI_P_qw: 0
KP_2: 0
Angle_0: 9
Gyro_3: 40
footPutDownPhase: 1
trunkYOffset: 0
KD_1: 0.18
doubleSupportRatio: 0.045
KP_P_qw: 0
footApexPhase: 0.5
footOvershootRatio: 0.05
trunkYOnlyInDoubleSupport: false
Gyro_0: 80
footPutDownZOffset: 0
KP_4: 0.3
footOvershootPhase: 0.85
trunkPitchPCoefForward: 0
trunkXOffsetPCoefTurn: 0
footDistance: 0.194
KP_0: 0.3
footRise: 0.05
KP_1: 0.2
trunkSwing: 0.2
freq: 1.72
KD_3: 0.19
trunkPitch: 0.1919862
trunkPhase: 0.6
trunkXOffset: -0.032