// Generated by gencpp from file zmp_walking_module_msgs/GetZMPParam.msg
// DO NOT EDIT!


#ifndef ZMP_WALKING_MODULE_MSGS_MESSAGE_GETZMPPARAM_H
#define ZMP_WALKING_MODULE_MSGS_MESSAGE_GETZMPPARAM_H

#include <ros/service_traits.h>


#include <zmp_walking_module_msgs/GetZMPParamRequest.h>
#include <zmp_walking_module_msgs/GetZMPParamResponse.h>


namespace zmp_walking_module_msgs
{

struct GetZMPParam
{

typedef GetZMPParamRequest Request;
typedef GetZMPParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetZMPParam
} // namespace zmp_walking_module_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zmp_walking_module_msgs::GetZMPParam > {
  static const char* value()
  {
    return "345512f6abd01a81ac305105720e1009";
  }

  static const char* value(const ::zmp_walking_module_msgs::GetZMPParam&) { return value(); }
};

template<>
struct DataType< ::zmp_walking_module_msgs::GetZMPParam > {
  static const char* value()
  {
    return "zmp_walking_module_msgs/GetZMPParam";
  }

  static const char* value(const ::zmp_walking_module_msgs::GetZMPParam&) { return value(); }
};


// service_traits::MD5Sum< ::zmp_walking_module_msgs::GetZMPParamRequest> should match 
// service_traits::MD5Sum< ::zmp_walking_module_msgs::GetZMPParam > 
template<>
struct MD5Sum< ::zmp_walking_module_msgs::GetZMPParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zmp_walking_module_msgs::GetZMPParam >::value();
  }
  static const char* value(const ::zmp_walking_module_msgs::GetZMPParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zmp_walking_module_msgs::GetZMPParamRequest> should match 
// service_traits::DataType< ::zmp_walking_module_msgs::GetZMPParam > 
template<>
struct DataType< ::zmp_walking_module_msgs::GetZMPParamRequest>
{
  static const char* value()
  {
    return DataType< ::zmp_walking_module_msgs::GetZMPParam >::value();
  }
  static const char* value(const ::zmp_walking_module_msgs::GetZMPParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zmp_walking_module_msgs::GetZMPParamResponse> should match 
// service_traits::MD5Sum< ::zmp_walking_module_msgs::GetZMPParam > 
template<>
struct MD5Sum< ::zmp_walking_module_msgs::GetZMPParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zmp_walking_module_msgs::GetZMPParam >::value();
  }
  static const char* value(const ::zmp_walking_module_msgs::GetZMPParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zmp_walking_module_msgs::GetZMPParamResponse> should match 
// service_traits::DataType< ::zmp_walking_module_msgs::GetZMPParam > 
template<>
struct DataType< ::zmp_walking_module_msgs::GetZMPParamResponse>
{
  static const char* value()
  {
    return DataType< ::zmp_walking_module_msgs::GetZMPParam >::value();
  }
  static const char* value(const ::zmp_walking_module_msgs::GetZMPParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZMP_WALKING_MODULE_MSGS_MESSAGE_GETZMPPARAM_H
