(cl:in-package kicking_module_msgs-msg)
(cl:export '(TORSO_X-VAL
          TORSO_X
          TORSO_Y-VAL
          TORSO_Y
          TORSO_Z-VAL
          TORSO_Z
          L_SHIFT_X-VAL
          L_SHIFT_X
          L_SHIFT_Y-VAL
          L_SHIFT_Y
          L_SHIFT_Z-VAL
          L_SHIFT_Z
          R_SHIFT_X-VAL
          R_SHIFT_X
          R_SHIFT_Y-VAL
          R_SHIFT_Y
          R_SHIFT_Z-VAL
          R_SHIFT_Z
          L_LIFT_X-VAL
          L_LIFT_X
          L_LIFT_Y-VAL
          L_LIFT_Y
          L_LIFT_Z-VAL
          L_LIFT_Z
          R_LIFT_X-VAL
          R_LIFT_X
          R_LIFT_Y-VAL
          R_LIFT_Y
          R_LIFT_Z-VAL
          R_LIFT_Z
          L_SWING_X-VAL
          L_SWING_X
          L_SWING_Y-VAL
          L_SWING_Y
          L_SWING_Z-VAL
          L_SWING_Z
          R_SWING_X-VAL
          R_SWING_X
          R_SWING_Y-VAL
          R_SWING_Y
          R_SWING_Z-VAL
          R_SWING_Z
          L_RETRACT_X-VAL
          L_RETRACT_X
          L_RETRACT_Y-VAL
          L_RETRACT_Y
          L_RETRACT_Z-VAL
          L_RETRACT_Z
          R_RETRACT_X-VAL
          R_RETRACT_X
          R_RETRACT_Y-VAL
          R_RETRACT_Y
          R_RETRACT_Z-VAL
          R_RETRACT_Z
          TORSO_PITCH-VAL
          TORSO_PITCH
          SHIFT_ROLL-VAL
          SHIFT_ROLL
          LIFT_ROLL-VAL
          LIFT_ROLL
          LIFT_PITCH-VAL
          LIFT_PITCH
          SWING_ROLL-VAL
          SWING_ROLL
          SWING_PITCH-VAL
          SWING_PITCH
          RETRACT_ROLL-VAL
          RETRACT_ROLL
          RETRACT_PITCH-VAL
          RETRACT_PITCH
          SHIFT_TIME-VAL
          SHIFT_TIME
          LIFT_TIME-VAL
          LIFT_TIME
          SWING_TIME-VAL
          SWING_TIME
          RETRACT_TIME-VAL
          RETRACT_TIME
          LANDING_TIME-VAL
          LANDING_TIME
          FINISHED_TIME-VAL
          FINISHED_TIME
))