(cl:in-package humanoid_league_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ROBOT_IDS-VAL
          ROBOT_IDS
          ROLE-VAL
          ROLE
          ACTION-VAL
          ACTION
          STATE-VAL
          STATE
          ROBOT_POSITIONS-VAL
          ROBOT_POSITIONS
          BALL_RELATIVE-VAL
          BALL_RELATIVE
          OPPGOAL_RELATIVE-VAL
          OPPGOAL_RELATIVE
          OPPONENT_ROBOT_A-VAL
          OPPONENT_ROBOT_A
          OPPONENT_ROBOT_B-VAL
          OPPONENT_ROBOT_B
          OPPONENT_ROBOT_C-VAL
          OPPONENT_ROBOT_C
          OPPONENT_ROBOT_D-VAL
          OPPONENT_ROBOT_D
          TEAM_ROBOT_A-VAL
          TEAM_ROBOT_A
          TEAM_ROBOT_B-VAL
          TEAM_ROBOT_B
          TEAM_ROBOT_C-VAL
          TEAM_ROBOT_C
          AVG_WALKING_SPEED-VAL
          AVG_WALKING_SPEED
          TIME_TO_POSITION_AT_BALL-VAL
          TIME_TO_POSITION_AT_BALL
          MAX_KICKING_DISTANCE-VAL
          MAX_KICKING_DISTANCE
          OFFENSIVE_SIDE-VAL
          OFFENSIVE_SIDE
))