(cl:defpackage mcl_localization-srv
  (:use )
  (:export
   "GETLOCPARAM"
   "<GETLOCPARAM-REQUEST>"
   "GETLOCPARAM-REQUEST"
   "<GETLOCPARAM-RESPONSE>"
   "GETLOCPARAM-RESPONSE"
   "SETLOCPARAM"
   "<SETLOCPARAM-REQUEST>"
   "SETLOCPARAM-REQUEST"
   "<SETLOCPARAM-RESPONSE>"
   "SETLOCPARAM-RESPONSE"
  ))

