// Generated by gencpp from file humanoid_league_msgs/BallInImage.msg
// DO NOT EDIT!


#ifndef HUMANOID_LEAGUE_MSGS_MESSAGE_BALLINIMAGE_H
#define HUMANOID_LEAGUE_MSGS_MESSAGE_BALLINIMAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace humanoid_league_msgs
{
template <class ContainerAllocator>
struct BallInImage_
{
  typedef BallInImage_<ContainerAllocator> Type;

  BallInImage_()
    : center()
    , diameter(0.0)
    , confidence(0.0)  {
    }
  BallInImage_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , diameter(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef double _diameter_type;
  _diameter_type diameter;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> const> ConstPtr;

}; // struct BallInImage_

typedef ::humanoid_league_msgs::BallInImage_<std::allocator<void> > BallInImage;

typedef boost::shared_ptr< ::humanoid_league_msgs::BallInImage > BallInImagePtr;
typedef boost::shared_ptr< ::humanoid_league_msgs::BallInImage const> BallInImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::humanoid_league_msgs::BallInImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::humanoid_league_msgs::BallInImage_<ContainerAllocator1> & lhs, const ::humanoid_league_msgs::BallInImage_<ContainerAllocator2> & rhs)
{
  return lhs.center == rhs.center &&
    lhs.diameter == rhs.diameter &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::humanoid_league_msgs::BallInImage_<ContainerAllocator1> & lhs, const ::humanoid_league_msgs::BallInImage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace humanoid_league_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90e95ed5b7c4ae20cbc638453cf31bb7";
  }

  static const char* value(const ::humanoid_league_msgs::BallInImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90e95ed5b7c4ae20ULL;
  static const uint64_t static_value2 = 0xcbc638453cf31bb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humanoid_league_msgs/BallInImage";
  }

  static const char* value(const ::humanoid_league_msgs::BallInImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Providing a (possible) ball in the image\n"
"\n"
"# Center point of the ball, the z-axis should be ignored (in pixel)\n"
"geometry_msgs/Point center\n"
"# Diameter of the ball (in pixel)\n"
"float64 diameter\n"
"\n"
"# A certainty rating between 0 and 1, where 1 is the surest.\n"
"# 0 means no ball was found\n"
"float32 confidence\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::humanoid_league_msgs::BallInImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.diameter);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallInImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humanoid_league_msgs::BallInImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::humanoid_league_msgs::BallInImage_<ContainerAllocator>& v)
  {
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "diameter: ";
    Printer<double>::stream(s, indent + "  ", v.diameter);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMANOID_LEAGUE_MSGS_MESSAGE_BALLINIMAGE_H
