// Generated by gencpp from file humanoid_league_msgs/ObstaclesInImage.msg
// DO NOT EDIT!


#ifndef HUMANOID_LEAGUE_MSGS_MESSAGE_OBSTACLESINIMAGE_H
#define HUMANOID_LEAGUE_MSGS_MESSAGE_OBSTACLESINIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <humanoid_league_msgs/ObstacleInImage.h>

namespace humanoid_league_msgs
{
template <class ContainerAllocator>
struct ObstaclesInImage_
{
  typedef ObstaclesInImage_<ContainerAllocator> Type;

  ObstaclesInImage_()
    : header()
    , obstacles()  {
    }
  ObstaclesInImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::humanoid_league_msgs::ObstacleInImage_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::humanoid_league_msgs::ObstacleInImage_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> const> ConstPtr;

}; // struct ObstaclesInImage_

typedef ::humanoid_league_msgs::ObstaclesInImage_<std::allocator<void> > ObstaclesInImage;

typedef boost::shared_ptr< ::humanoid_league_msgs::ObstaclesInImage > ObstaclesInImagePtr;
typedef boost::shared_ptr< ::humanoid_league_msgs::ObstaclesInImage const> ObstaclesInImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace humanoid_league_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'humanoid_league_msgs': ['/home/alfarobi/alfarobi_ws/src/ALFAROBI-Communication/humanoid_league_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0807f4239b3cd59edd38069d2f956035";
  }

  static const char* value(const ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0807f4239b3cd59eULL;
  static const uint64_t static_value2 = 0xdd38069d2f956035ULL;
};

template<class ContainerAllocator>
struct DataType< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humanoid_league_msgs/ObstaclesInImage";
  }

  static const char* value(const ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The header is included to get the time stamp for later use in tf\n\
std_msgs/Header header\n\
\n\
ObstacleInImage[] obstacles\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: humanoid_league_msgs/ObstacleInImage\n\
# An obstacle in the image, which can be a robot, a human or something else\n\
\n\
# Main color of the obstacle, to differentiate between robots and other things like human legs\n\
# Something we cant classify\n\
uint8 UNDEFINED = 0\n\
# Robot without known color\n\
uint8 ROBOT_UNDEFINED = 1\n\
uint8 ROBOT_MAGENTA = 2\n\
uint8 ROBOT_CYAN = 3\n\
# A human legs, e.g. from the referee\n\
uint8 HUMAN = 4\n\
# Black poles which are normally used for technical challenges\n\
uint8 POLE = 5\n\
uint8 color\n\
\n\
# The number of the robot, if it is a robot and if it can be read. Put in -1 if not known\n\
uint8 playerNumber\n\
\n\
# The corresponding section in the image\n\
geometry_msgs/Point top_left\n\
uint8 height\n\
uint8 width\n\
\n\
# A certainty rating between 0 and 1, where 1 is the surest.\n\
float32 confidence\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstaclesInImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::humanoid_league_msgs::ObstaclesInImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::humanoid_league_msgs::ObstacleInImage_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMANOID_LEAGUE_MSGS_MESSAGE_OBSTACLESINIMAGE_H
