(cl:defpackage feedback_msgs-srv
  (:use )
  (:export
   "GETFEEDBACKPARAM"
   "<GETFEEDBACKPARAM-REQUEST>"
   "GETFEEDBACKPARAM-REQUEST"
   "<GETFEEDBACKPARAM-RESPONSE>"
   "GETFEEDBACKPARAM-RESPONSE"
   "SETFEEDBACKPARAM"
   "<SETFEEDBACKPARAM-REQUEST>"
   "SETFEEDBACKPARAM-REQUEST"
   "<SETFEEDBACKPARAM-RESPONSE>"
   "SETFEEDBACKPARAM-RESPONSE"
  ))

