(cl:in-package zmp_walking_module_msgs-msg)
(cl:export '(FEEDBACK_-VAL
          FEEDBACK_
          L_SHIFT-VAL
          L_SHIFT
          L_LIFT-VAL
          L_LIFT
          L_P_KICK-VAL
          L_P_KICK
          L_P_COOL-VAL
          L_P_COOL
          R_SHIFT-VAL
          R_SHIFT
          R_LIFT-VAL
          R_LIFT
          R_P_KICK-VAL
          R_P_KICK
          R_P_COOL-VAL
          R_P_COOL
          KP-VAL
          KP
          KD-VAL
          KD
          TH1-VAL
          TH1
          TH2-VAL
          TH2
          ACC-VAL
          ACC
          KPP-VAL
          KPP
          KPR-VAL
          KPR
          KDP-VAL
          KDP
          KDR-VAL
          KDR
          KI-VAL
          KI
          ZMP_VX-VAL
          ZMP_VX
          ZMP_VY-VAL
          ZMP_VY
          ZMP_VPHI-VAL
          ZMP_VPHI
          M_ZMP_VX-VAL
          M_ZMP_VX
          M_ZMP_VY-VAL
          M_ZMP_VY
          M_ZMP_VPHI-VAL
          M_ZMP_VPHI
          ZMP_VX_MAN-VAL
          ZMP_VX_MAN
          ZMP_USEGYRO-VAL
          ZMP_USEGYRO
          ARM_PITCH-VAL
          ARM_PITCH
          ARM_ROLL-VAL
          ARM_ROLL
          ARM_ELBOW-VAL
          ARM_ELBOW
          SUPP_FRONT-VAL
          SUPP_FRONT
          SUPP_FRONT2-VAL
          SUPP_FRONT2
          SUPP_TURN-VAL
          SUPP_TURN
          SUPP_SIDE_X-VAL
          SUPP_SIDE_X
          SUPP_SIDE_Y-VAL
          SUPP_SIDE_Y
          SUPP_X-VAL
          SUPP_X
          SUPP_Y-VAL
          SUPP_Y
          SUPPMOD_Y_INIT-VAL
          SUPPMOD_Y_INIT
          TURNCOMP_THRS-VAL
          TURNCOMP_THRS
          TURN_COMP-VAL
          TURN_COMP
          ACCEL_COMP-VAL
          ACCEL_COMP
          FRONT_COMP-VAL
          FRONT_COMP
          HIPROLL_COMP-VAL
          HIPROLL_COMP
          TSTEP-VAL
          TSTEP
          TZMP-VAL
          TZMP
          VELFAST_FORWARD-VAL
          VELFAST_FORWARD
          VELFAST_TURN-VAL
          VELFAST_TURN
          ANGKLE_SUPP_FACTOR-VAL
          ANGKLE_SUPP_FACTOR
          FOOT_Y-VAL
          FOOT_Y
          FOOT_X-VAL
          FOOT_X
          STAND_OFFSET-VAL
          STAND_OFFSET
          BODY_HEIGHT-VAL
          BODY_HEIGHT
          STEP_HEIGHT-VAL
          STEP_HEIGHT
          BELLY_ROLL-VAL
          BELLY_ROLL
          BELLY_HIP-VAL
          BELLY_HIP
          BODYTILT-VAL
          BODYTILT
          ANKLEX_FACT-VAL
          ANKLEX_FACT
          ANKLEX_DEADBAND-VAL
          ANKLEX_DEADBAND
          ANKLEX_MAXVAL-VAL
          ANKLEX_MAXVAL
          ANKLEY_FACT-VAL
          ANKLEY_FACT
          ANKLEY_DEADBAND-VAL
          ANKLEY_DEADBAND
          ANKLEY_MAXVAL-VAL
          ANKLEY_MAXVAL
          KNEEX_FACT-VAL
          KNEEX_FACT
          KNEEX_DEADBAND-VAL
          KNEEX_DEADBAND
          KNEEX_MAXVAL-VAL
          KNEEX_MAXVAL
          HIPY_FACT-VAL
          HIPY_FACT
          HIPY_DEADBAND-VAL
          HIPY_DEADBAND
          HIPY_MAXVAL-VAL
          HIPY_MAXVAL
          ARMY_FACT-VAL
          ARMY_FACT
          ARMY_DEADBAND-VAL
          ARMY_DEADBAND
          ARMY_MAXVAL-VAL
          ARMY_MAXVAL
          ARMX_FACT-VAL
          ARMX_FACT
          ARMX_DEADBAND-VAL
          ARMX_DEADBAND
          ARMX_MAXVAL-VAL
          ARMX_MAXVAL
          BALLPOSX-VAL
          BALLPOSX
          BALLPOSY-VAL
          BALLPOSY
          BALLPOSZ-VAL
          BALLPOSZ
          GOALPOSX-VAL
          GOALPOSX
          GOALPOSY-VAL
          GOALPOSY
          GOALPOSZ-VAL
          GOALPOSZ
          POWER-VAL
          POWER
          TRETRACT-VAL
          TRETRACT
          TKICK-VAL
          TKICK
          TRISING-VAL
          TRISING
          TDOWN-VAL
          TDOWN
))