(cl:defpackage zmp_walking_module_msgs-srv
  (:use )
  (:export
   "GETZMPPARAM"
   "<GETZMPPARAM-REQUEST>"
   "GETZMPPARAM-REQUEST"
   "<GETZMPPARAM-RESPONSE>"
   "GETZMPPARAM-RESPONSE"
   "SETZMPPARAM"
   "<SETZMPPARAM-REQUEST>"
   "SETZMPPARAM-REQUEST"
   "<SETZMPPARAM-RESPONSE>"
   "SETZMPPARAM-RESPONSE"
  ))

