(cl:defpackage kicking_module_msgs-srv
  (:use )
  (:export
   "GETKICKINGPARAM"
   "<GETKICKINGPARAM-REQUEST>"
   "GETKICKINGPARAM-REQUEST"
   "<GETKICKINGPARAM-RESPONSE>"
   "GETKICKINGPARAM-RESPONSE"
   "SETKICKINGPARAM"
   "<SETKICKINGPARAM-REQUEST>"
   "SETKICKINGPARAM-REQUEST"
   "<SETKICKINGPARAM-RESPONSE>"
   "SETKICKINGPARAM-RESPONSE"
  ))

