printKickVar: false
feedbackActive: false
initPose: false
FKfromgoalPos: true
printOP3posFK: false
printOP3posFK_LSSP: false
printOP3posFK_RSSP: false
printOP3rotFK: false
printOP3rotFK_LSSP: false
printOP3rotFK_RSSP: false
printOP3Joints: false
printOP3globalInertia: false
useIMU: true
L_Tilt: 10
R_Tilt: 10
L_SP_Roll: 10
R_SP_Roll: -15
L_SP_Pitch: 10
R_SP_Pitch: 10
L_X_Manip: 0.02
R_X_Manip: 0.01
ballPosX: 0.35
ballPosZ: 0.09