const_ground_push: -0
halt_pos_foot_roll_ext: 0.02
propt_ground_push: 0
lateral_swg_offset: 0.05
lateral_swg: 0.1
lateral_hip_swg: 0.05
trng_lateral_swg_offset: 0.015
fwd_lean: 0.2
rotational_swg_offset: 0.08
sagittal_acc: 0.0085
lateral_prop_step_freq: 0
rotational_swg: 0.8
sagittal_swg_fwd: 0.173
halt_pos_leg_roll_ext: 0.12
swing_start: 0
propt_step_height: 0.12
rotational_acc: 0.009
swing_stop: 1
fwd_trng_lean: -0.07
halt_pos_foot_pitch_ext: -0.14
halt_pos_leg_ext: 0.143
bwd_lean: -0.6
sagittal_swg_bwd: 0.12
gait_vel_limit: 3.5
const_step_height: 0.17
lateral_acc: 0.01
const_step_freq: 0.11
sagittal_prop_step_freq: 0.013
halt_pos_leg_pitch_ext: -0.06