// Generated by gencpp from file dnn_detector/SetParameters.msg
// DO NOT EDIT!


#ifndef DNN_DETECTOR_MESSAGE_SETPARAMETERS_H
#define DNN_DETECTOR_MESSAGE_SETPARAMETERS_H

#include <ros/service_traits.h>


#include <dnn_detector/SetParametersRequest.h>
#include <dnn_detector/SetParametersResponse.h>


namespace dnn_detector
{

struct SetParameters
{

typedef SetParametersRequest Request;
typedef SetParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParameters
} // namespace dnn_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dnn_detector::SetParameters > {
  static const char* value()
  {
    return "6ef3ab2b457693e716fc437aa9628429";
  }

  static const char* value(const ::dnn_detector::SetParameters&) { return value(); }
};

template<>
struct DataType< ::dnn_detector::SetParameters > {
  static const char* value()
  {
    return "dnn_detector/SetParameters";
  }

  static const char* value(const ::dnn_detector::SetParameters&) { return value(); }
};


// service_traits::MD5Sum< ::dnn_detector::SetParametersRequest> should match 
// service_traits::MD5Sum< ::dnn_detector::SetParameters > 
template<>
struct MD5Sum< ::dnn_detector::SetParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dnn_detector::SetParameters >::value();
  }
  static const char* value(const ::dnn_detector::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dnn_detector::SetParametersRequest> should match 
// service_traits::DataType< ::dnn_detector::SetParameters > 
template<>
struct DataType< ::dnn_detector::SetParametersRequest>
{
  static const char* value()
  {
    return DataType< ::dnn_detector::SetParameters >::value();
  }
  static const char* value(const ::dnn_detector::SetParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dnn_detector::SetParametersResponse> should match 
// service_traits::MD5Sum< ::dnn_detector::SetParameters > 
template<>
struct MD5Sum< ::dnn_detector::SetParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dnn_detector::SetParameters >::value();
  }
  static const char* value(const ::dnn_detector::SetParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dnn_detector::SetParametersResponse> should match 
// service_traits::DataType< ::dnn_detector::SetParameters > 
template<>
struct DataType< ::dnn_detector::SetParametersResponse>
{
  static const char* value()
  {
    return DataType< ::dnn_detector::SetParameters >::value();
  }
  static const char* value(const ::dnn_detector::SetParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DNN_DETECTOR_MESSAGE_SETPARAMETERS_H
