(cl:in-package quintic_walk_msgs-msg)
(cl:export '(FREQ-VAL
          FREQ
          DOUBLESUPPORTRATIO-VAL
          DOUBLESUPPORTRATIO
          FOOTDISTANCE-VAL
          FOOTDISTANCE
          FOOTRISE-VAL
          FOOTRISE
          FOOTPUTDOWNZOFFSET-VAL
          FOOTPUTDOWNZOFFSET
          FOOTPUTDOWNPHASE-VAL
          FOOTPUTDOWNPHASE
          FOOTAPEXPHASE-VAL
          FOOTAPEXPHASE
          FOOTOVERSHOOTRATIO-VAL
          FOOTOVERSHOOTRATIO
          FOOTOVERSHOOTPHASE-VAL
          FOOTOVERSHOOTPHASE
          TRUNKHEIGHT-VAL
          TRUNKHEIGHT
          TRUNKPITCH-VAL
          TRUNKPITCH
          TRUNKPHASE-VAL
          TRUNKPHASE
          TRUNKXOFFSET-VAL
          TRUNKXOFFSET
          TRUNKYOFFSET-VAL
          TRUNKYOFFSET
          TRUNKSWING-VAL
          TRUNKSWING
          TRUNKPAUSE-VAL
          TRUNKPAUSE
          TRUNKXOFFSETPCOEFFORWARD-VAL
          TRUNKXOFFSETPCOEFFORWARD
          TRUNKXOFFSETPCOEFTURN-VAL
          TRUNKXOFFSETPCOEFTURN
          TRUNKPITCHPCOEFFORWARD-VAL
          TRUNKPITCHPCOEFFORWARD
          TRUNKPITCHPCOEFTURN-VAL
          TRUNKPITCHPCOEFTURN
          TRUNKYONLYINDOUBLESUPPORT-VAL
          TRUNKYONLYINDOUBLESUPPORT
          XMOVE-VAL
          XMOVE
          YMOVE-VAL
          YMOVE
          ZMOVE-VAL
          ZMOVE
          MODE-VAL
          MODE
          TUNING-VAL
          TUNING
          D_ANKLE_P_QW-VAL
          D_ANKLE_P_QW
          D_KNEE_QW-VAL
          D_KNEE_QW
          D_HIP_P_QW-VAL
          D_HIP_P_QW
          KP_P_QW-VAL
          KP_P_QW
          KD_P_QW-VAL
          KD_P_QW
          KI_P_QW-VAL
          KI_P_QW
          SHOULDERGAIN_QW-VAL
          SHOULDERGAIN_QW
          SETPOINTPITCH-VAL
          SETPOINTPITCH
          PITCH_ERROR_TOL-VAL
          PITCH_ERROR_TOL
          KP_X_QW-VAL
          KP_X_QW
          KD_X_QW-VAL
          KD_X_QW
          KI_X_QW-VAL
          KI_X_QW
          ANGLE_0-VAL
          ANGLE_0
          ANGLE_1-VAL
          ANGLE_1
          ANGLE_2-VAL
          ANGLE_2
          ANGLE_3-VAL
          ANGLE_3
          ANGLE_4-VAL
          ANGLE_4
          KD_0-VAL
          KD_0
          KD_1-VAL
          KD_1
          KD_2-VAL
          KD_2
          KD_3-VAL
          KD_3
          KD_4-VAL
          KD_4
          GYRO_0-VAL
          GYRO_0
          GYRO_1-VAL
          GYRO_1
          GYRO_2-VAL
          GYRO_2
          GYRO_3-VAL
          GYRO_3
          GYRO_4-VAL
          GYRO_4
          KP_0-VAL
          KP_0
          KP_1-VAL
          KP_1
          KP_2-VAL
          KP_2
          KP_3-VAL
          KP_3
          KP_4-VAL
          KP_4
))