(cl:in-package feedback_msgs-msg)
(cl:export '(BODY_HEIGHT-VAL
          BODY_HEIGHT
          BODY_TILT-VAL
          BODY_TILT
          LEG_X-VAL
          LEG_X
          LEG_Y-VAL
          LEG_Y
          LEG_Z-VAL
          LEG_Z
          LEG_R_Z-VAL
          LEG_R_Z
          LEG_L_Z-VAL
          LEG_L_Z
          R_ROLL-VAL
          R_ROLL
          L_ROLL-VAL
          L_ROLL
          SETPOINT_PITCH-VAL
          SETPOINT_PITCH
          SETPOINT_ROLL-VAL
          SETPOINT_ROLL
          GAIN_ANGLE_PITCH-VAL
          GAIN_ANGLE_PITCH
          GAIN_ANGLE_ROLL-VAL
          GAIN_ANGLE_ROLL
          GAIN_VELOCITY_PITCH-VAL
          GAIN_VELOCITY_PITCH
          GAIN_VELOCITY_ROLL-VAL
          GAIN_VELOCITY_ROLL
          GAIN_INTEGRAL_PITCH-VAL
          GAIN_INTEGRAL_PITCH
          GAIN_INTEGRAL_ROLL-VAL
          GAIN_INTEGRAL_ROLL
))