(cl:in-package op3_walking_module_msgs-msg)
(cl:export '(INIT_X_OFFSET-VAL
          INIT_X_OFFSET
          INIT_Y_OFFSET-VAL
          INIT_Y_OFFSET
          INIT_Z_OFFSET-VAL
          INIT_Z_OFFSET
          INIT_ROLL_OFFSET-VAL
          INIT_ROLL_OFFSET
          INIT_PITCH_OFFSET-VAL
          INIT_PITCH_OFFSET
          INIT_YAW_OFFSET-VAL
          INIT_YAW_OFFSET
          R_X_OFFSET-VAL
          R_X_OFFSET
          R_Y_OFFSET-VAL
          R_Y_OFFSET
          R_Z_OFFSET-VAL
          R_Z_OFFSET
          R_ROLL_OFFSET-VAL
          R_ROLL_OFFSET
          R_PITCH_OFFSET-VAL
          R_PITCH_OFFSET
          R_YAW_OFFSET-VAL
          R_YAW_OFFSET
          L_X_OFFSET-VAL
          L_X_OFFSET
          L_Y_OFFSET-VAL
          L_Y_OFFSET
          L_Z_OFFSET-VAL
          L_Z_OFFSET
          L_ROLL_OFFSET-VAL
          L_ROLL_OFFSET
          L_PITCH_OFFSET-VAL
          L_PITCH_OFFSET
          L_YAW_OFFSET-VAL
          L_YAW_OFFSET
          PERIOD_TIME-VAL
          PERIOD_TIME
          DSP_RATIO-VAL
          DSP_RATIO
          STEP_FB_RATIO-VAL
          STEP_FB_RATIO
          X_MOVE_AMPLITUDE-VAL
          X_MOVE_AMPLITUDE
          Y_MOVE_AMPLITUDE-VAL
          Y_MOVE_AMPLITUDE
          Z_MOVE_AMPLITUDE-VAL
          Z_MOVE_AMPLITUDE
          ANGLE_MOVE_AMPLITUDE-VAL
          ANGLE_MOVE_AMPLITUDE
          MOVE_AIM_ON-VAL
          MOVE_AIM_ON
          BALANCE_ENABLE-VAL
          BALANCE_ENABLE
          BALANCE_HIP_ROLL_GAIN-VAL
          BALANCE_HIP_ROLL_GAIN
          BALANCE_KNEE_GAIN-VAL
          BALANCE_KNEE_GAIN
          BALANCE_ANKLE_ROLL_GAIN-VAL
          BALANCE_ANKLE_ROLL_GAIN
          BALANCE_ANKLE_PITCH_GAIN-VAL
          BALANCE_ANKLE_PITCH_GAIN
          Y_SWAP_AMPLITUDE-VAL
          Y_SWAP_AMPLITUDE
          Z_SWAP_AMPLITUDE-VAL
          Z_SWAP_AMPLITUDE
          ARM_SWING_GAIN-VAL
          ARM_SWING_GAIN
          PELVIS_OFFSET-VAL
          PELVIS_OFFSET
          HIP_PITCH_OFFSET-VAL
          HIP_PITCH_OFFSET
          KP_P-VAL
          KP_P
          KD_P-VAL
          KD_P
          KI_P-VAL
          KI_P
          D_ANKLE_P-VAL
          D_ANKLE_P
          D_KNEE-VAL
          D_KNEE
          D_HIP_P-VAL
          D_HIP_P
          KP_R-VAL
          KP_R
          KD_R-VAL
          KD_R
          KI_R-VAL
          KI_R
          D_ANKLE_R-VAL
          D_ANKLE_R
          D_HIP_R-VAL
          D_HIP_R
          SHOULDER_GAIN-VAL
          SHOULDER_GAIN
          P_GAIN-VAL
          P_GAIN
          I_GAIN-VAL
          I_GAIN
          D_GAIN-VAL
          D_GAIN
          ZMP_VX-VAL
          ZMP_VX
          ZMP_VY-VAL
          ZMP_VY
          ZMP_VPHI-VAL
          ZMP_VPHI
          ZMP_USEGYRO-VAL
          ZMP_USEGYRO
))